### PR TITLE
Show permissions in phpBB 3.1.7+

### PR DESCRIPTION
**Pull request by Tatiana5**

### CODE REVIEW

**Comment by Inkoming** [comment]
Can you explain what's this and why should we add it to our code?

**Comment by Tatiana5** [comment]
If not added permission in the event core.permission, then permission don't pass check, and permission is not displayed on the forum

https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/acp/auth.php#L1147 - check exist permission in the object or not exist
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/acp/auth.php#L1111 - object

acl.permissions - file root/phpbb/permissions.php
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/permissions.php#L222 - list standart permissions
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/permissions.php#L43
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/permissions.php#L66
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/permissions.php#L70 - and permissions of event core.permission

**Comment by Galixte** [comment]
Hi is it merged in 2.1.x version @Sajaki ?

**Comment by avandenberghe** [comment]
yes, it is.
https://github.com/Sajaki/RecentTopics/commit/c4450935919d0bf125febbc44485d434de8ae294

**Comment by Galixte** [comment]
Thanks, @Tatiana5 so it can be closed now ?

**Pull request closed without merging**
